apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-d4ko
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0026-tenant/tkrw-pr712-0075-0026-app/devfile-sample-d4ko@sha256:d711602cd3a67dcd53b351e5ae204af1e357f0bb130d71eb07a228aecdf80da7
        name: my-nodejs
        resources: {}
status: {}
